version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_service
    environment:
      - APP_DB_HOST=postgres
      - APP_DB_PORT=5432
      - APP_DB_USER=${DB_USER}
      - APP_DB_PASSWORD=${DB_PASSWORD}
      - APP_DB_NAME=${DB_NAME}
      - APP_DB_SSLMODE=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["--server.host=0.0.0.0", "--server.port=8080"]
    restart: unless-stopped
    networks:
      - bank_network

  postgres:
    image: postgres:latest
    container_name: bank_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank_network

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge